### ISSUE TITLE
Serialosc error

### ISSUE THREAD

**Issue by findzen** [monome-community/parc#1]
OS X 10.10.4, new grid, just ran the installer and attempted to load Parc. It won't connect to the grid, I'm assuming because of the first error below.

```
bpatcher: bpatcher: error loading patcher serialosc.maxpat
bpatcher: patchcord outlet out of range: deleting patchcord
bpatcher: patchcord outlet out of range: deleting patchcord
bpatcher: patchcord inlet out of range: deleting patchcord
bpatcher: patchcord inlet out of range: deleting patchcord
```

Do I need an older version of serialosc to run this?

**Comment by tehn** [comment]
get max 7 and it is included

**Comment by findzen** [comment]
Thanks, that did the trick. Nice work!
